replicaCount: 1

image:
  repository: orderflow-aiops-notification-service
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  port: 8080

env: []

healthPath: /healthz

probes:
  startup:
    failureThreshold: 30
    periodSeconds: 2
  readiness:
    periodSeconds: 5
  liveness:
    periodSeconds: 10

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
